// Generated by gen-meta.js
const appName = 'ClipCC';

const appVersion = '3.0.0';
const appVersionSimple = '3.0';
const appVersionFull = '3.0.0-b202105142217';
const compileTime = '2021-05-14T14:17:39.189Z'

export {
    appVersion, appVersionSimple, appVersionFull, compileTime
};
