const fs = require('fs');
const path = require('path');
const childProcess = require('child_process');
const packageInfo = require('./package.json');

const isProd = process.env.NODE_ENV === 'production' ? true : false;
const time = new Date();

let commitHash = 'unknown';
try {
    commitHash = childProcess.execSync('git show -s --format=%h').toString()
        .trim();
} catch (err) {}

const code = `// Generated by gen-meta.js
const appName = 'ClipCC';

const isProd = ${isProd};
const appVersion = '3.1.1';
const appVersionSimple = '3.1.1';
const appVersionFull = '3.1.1-${commitHash}-${time.toISOString()}';
const compileTime = '${time.toISOString()}';
const commitHash = '${commitHash}';

export {
    isProd, appVersion, appVersionFull, compileTime, commitHash
};
`;

fs.writeFileSync(path.join(__dirname, 'src/lib/app-info.js'), code);

const ENABLE_PWA = process.env.ENABLE_PWA;

if (ENABLE_PWA) {
    let data = fs.readFileSync(path.join(__dirname, 'static/sw.js'), {encoding: 'utf-8'});
    data = data.replace('gen@appVer', compileId);
    fs.writeFileSync(path.join(__dirname, 'static/sw.build.js'), data);
}
