const fs = require('fs');
const path = require('path');
const moment = require('moment');
const childProcess = require('child_process');
const packageInfo = require('./package.json');

const time = new Date();
const compileId = moment(time).format('YYYYMMDDHHmm');

const commitHash = childProcess.execSync('git show -s --format=%h').toString().trim();

const code = `// Generated by gen-meta.js
const appName = 'ClipCC';

const appVersion = '${packageInfo.version}';
const appVersionFull = '${packageInfo.version}-b${compileId}';
const compileTime = '${time.toISOString()}';
const commitHash = '${commitHash}';

export {
    appVersion, appVersionFull, compileTime, commitHash
};
`;

fs.writeFileSync(path.join(__dirname, 'src/lib/app-info.js'), code);

const ENABLE_PWA = process.env.ENABLE_PWA;

if (ENABLE_PWA) {
    let data = fs.readFileSync(path.join(__dirname, 'static/sw.js'), { encoding: 'utf-8' });
    data = data.replace('gen@appVer', compileId);
    fs.writeFileSync(path.join(__dirname, 'static/sw.build.js'), data);
}
