/* eslint-disable linebreak-style */
export const contributorList = {
    tips: '(In no particular order)',
    alexcui: 'Alex Cui - G-Editor developer / ClipCC lead developer, ClipCommunity developer',
    sinangentoo: 'SinanGentoo - G-Editor / ClipCC lead developer，ClipCommunity developer，Clipteam founder',
    solstice23: 'solstice23 - G-Editor lead developer',
    e4361: 'e4361 - G-Editor developer',
    sparrowhe: 'SparrowHe - G-Editor / ClipCC developer，advocacy support，mascot',
    stevexmh: 'SteveXMH - ClipCC developer',
    zerlight: 'Zerlight - ClipCC artistic support',
    hydrostic: 'Hydrostic - ClipCC developer， ClipCommunity lead developer',
    frank782: 'frank_782 ClipCC developer',
    bleshi: 'BleShi - Clipteam\'s domain/server sponsor',
    jasonjia: 'JasonJia - ClipCC developer，advocacy support',
    soilzhu: 'SoilZhu - ClipCC artistic support, chuunibyo mode contributor.',
    waterblock79: 'Waterblock79 - ClipCC extension store developer',
    yuan3old: 'Yuan3old - ClipCC advocacy support',
    someoneyoung: 'Someone_Young - ClipCC advocacy support',
    lmlanmei: 'LMLanmei - ClipCC Traditional Chinese i18n contributor',
    xiaoji4093: 'xiaoji4093 - ClipCC sponsor(clash)',
    jasonxu: 'JasonXu - ClipCC sponsor(200 CNY)',
    unknown: 'Unknown contributor - ClipCC sponsor(60 CNY)',
    lyricepic: 'LyricEpic - ClipCC sponsor(19.98 CNY)',
    cyarice: 'Cya_Rice - ClipCC sponsor(11.4 CNY)',
    afadian: 'Afadian_c5qE - ClipCC sponsor (30 CNY)',
    mbzzw: 'mbzzw - ClipCommunity sponsor(60 CNY)',
    august: 'All SPONSORS who helped the clipteam through the difficult times in August 2021',
    you: 'And you'
};
